version: 0.1.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
platform:
- x86
- x64
matrix:
  fast_finish: true
environment:
  matrix:
    - build_dir: ""
    - build_dir: "x64/"
build:
  project: ./DRAK-0.sln
  parallel: true
  verbosity: minimal
cache: c:\tools\vcpkg
init:
 - cd "C:\Tools\vcpkg"
 - git pull
 - .\bootstrap-vcpkg.bat
 - if $(platform)==x86 (
 -  vcpkg install sfml:x86-windows-static
 - ) ELSE (
 -  if $(platform)==x64 (
 -   vcpkg install sfml:x64-windows-static
 -  )
 - )
 - cd "C:\projects\drak-0"
artifacts:
- path: $(build_dir)$(configuration)
  name: drak-0_$(platform)_$(configuration)
  type: zip
deploy:
- provider: GitHub
  description: AppVeyor can now build DRAK-0
  auth_token:
    secure: 630hO1MXqA8+thTM4TJKeUGHCf/vk+9lYR7ugg4S52z8ZrLX+ApvvXBjClN2rwDG
  artifact: drak-0_$(platform)_$(configuration)
  draft: true
  prerelease: true
