#version: 0.1.{build}
image: Visual Studio 2017
configuration:
 - Debug
 - Release
platform:
 - x86
 - x64
environment:
  proj_platform: $(platform)
  proj_configuration: $(configuration)
matrix:
  fast_finish: true
build:
  project: ./DRAK-0.sln
  parallel: true
  verbosity: minimal
cache:
 - c:\tools\vcpkg\installed\
 - c:\projects\drak-0\drak-0\obj\
install:
 - cd "C:\Tools\vcpkg"
 - git pull
 - .\bootstrap-vcpkg.bat
 - if "%proj_platform%"=="x86" ( vcpkg install sfml:x86-windows-static ) else ( if "%proj_platform%"=="x64" ( vcpkg install sfml:x64-windows-static ) )
 - cd "C:\projects\drak-0"
after_build:
 - del /S "C:\projects\DRAK-0\%proj_platform%\%proj_configuration%\*.iobj"
 - del /S "C:\projects\DRAK-0\%proj_platform%\%proj_configuration%\*.ipdb"
 - del /S "C:\projects\DRAK-0\%proj_platform%\%proj_configuration%\*.ilk"
 - del /S "C:\projects\DRAK-0\%proj_platform%\%proj_configuration%\*.pdb"
artifacts:
 - path: $(platform)/$(configuration)
   name: drak-0_$(platform)_$(configuration)
deploy:
 - provider: GitHub
   description: AppVeyor Release for DRAK-0
   auth_token:
     secure: 630hO1MXqA8+thTM4TJKeUGHCf/vk+9lYR7ugg4S52z8ZrLX+ApvvXBjClN2rwDG
   artifact: drak-0_$(platform)_$(configuration)
   draft: true
   prelease: true

for:
- 
  branches:
    only:
      - master
  version: 0.1.{build}

- 
  branches:
    only:
      - dev
  version: 0.1.x-$(APPVEYOR_REPO_COMMIT)
