version: 0.1.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
platform:
- x86
- x64
environment:
  proj_platform: $(platform)
  proj_configuration: $(configuration)
matrix:
  fast_finish: true
build:
  project: ./DRAK-0.sln
  parallel: true
  verbosity: minimal
cache: c:\tools\vcpkg
init:
 - if %proj_platform%=="x86" ( echo "x86" ) ELSE ( if %proj_platform%=="x64" ( echo "x64" ) )
 - cd "C:\Tools\vcpkg"
 - git pull
 - .\bootstrap-vcpkg.bat
 - if %proj_platform%=="x86" ( vcpkg install sfml:x86-windows-static ) ELSE ( if %proj_platform%=="x64" ( vcpkg install sfml:x64-windows-static ) )
 - cd "C:\projects\drak-0"
artifacts:
- path: $(platform)$(configuration)
  name: drak-0_$(platform)_$(configuration)
  type: zip
deploy:
- provider: GitHub
  description: AppVeyor can now build DRAK-0
  auth_token:
    secure: 630hO1MXqA8+thTM4TJKeUGHCf/vk+9lYR7ugg4S52z8ZrLX+ApvvXBjClN2rwDG
  artifact: drak-0_$(platform)_$(configuration)
  draft: true
  prerelease: true
