version: 0.1.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
platform:
- x86
- x64
build:
  project: ./DRAK-0.sln
  parallel: true
  verbosity: normal
cache: c:\tools\vcpkg\installed\
init:
 - vcpkg update
 - vcpkg install sfml:x86-windows-static
 - vcpkg install sfml:x64-windows-static